version: '3.8'
services:
  neo4j:
    image: neo4j:5-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}

  app:
    build: ..
    env_file:
      - ../config/.env
    volumes:
      - /usr/local/bin/ollama:/usr/local/bin/ollama:ro
      - ~/.ollama/models:/root/.ollama/models:ro
    depends_on:
      - neo4j
    command: python orchestrator/mcp_workflow.py
